### ISSUE TITLE
The Garage door shows as open in Home app also won't open or close

### ISSUE THREAD

**Issue by Slowmaro** [iAnatoly/homebridge-aladdin-connect-garage-door#10]
Hi,

Garage door has a false "Open" status, also when you try to send command it won't open or close.

**Comment by apexad** [comment]
Is the Genie Aladdin Connect app showing the correct status?  if it is showing the incorrect status, diagnose the issues with your hardware as this is not an issue with the plugin.

If it is showing the correct status in the Genie Aladdin connect app and this plugin is not, please note in the README that you must use the 'main' account and not a sub-account.  Check your configuration (including username/password) and confirm it is correct.

**Comment by apexad** [comment]
If after confirming everything should be working with plugin and you are still getting a false 'OPEN' status, please turn on `log_polling` and `allow_debug` and provide us with the logs so we can figure out what may be wrong.
