### ISSUE TITLE
Genie app update

### ISSUE THREAD

**Issue by jbitzerjr** [iAnatoly/homebridge-aladdin-connect-garage-door#11]
Is this plugin actively updated?  I haven't been able to control my doors through homebridge since genie released the new app.

**Comment by apexad** [comment]
As far as I can tell the new app is just a UI change.  No changes to the underlying API which is what this plugin uses.

Confirm your hardware is still all working correctly (using the native app) and that your login/password is still correct.  Remember, that we currently have not tested shared accounts, only the main account is known to work.

**Comment by jbitzerjr** [comment]
THanks, man!  I must have reversed the accounts when the app messed up all my passwords and everything needed reset, you rule.
