### ISSUE TITLE
Documentation tweak (device and garage numbers)

### ISSUE THREAD

**Issue by droffsite** [iAnatoly/homebridge-aladdin-connect-garage-door#12]
First things first: thanks for the plugin! I can finally control 2 different garage door openers from one place.

In the documentation, you have device_number described as door number. It would appear from my setup that that is the number of the configured Genie device (the main unit), not the door. The other, garage_number appears to map to the door (as numbered, in my case, by the labels on the back of the device).

I have a single Genie controller with one door (myQ opener, doesn't actually work with the Genie) connected to Door 1 (on the back of the unit) and another (older Liftmaster, the one I want to control) to Door 3. The configuration that got this to work for me was device_number=0 and garage_number=3.

Thanks again!

**Comment by apexad** [comment]
You are right.  Sorry about this mixup in the README.  It has been fixed.
