### ISSUE TITLE
Incorrect Status and doesn't open/close

### ISSUE THREAD

**Issue by nefarious-vw** [iAnatoly/homebridge-aladdin-connect-garage-door#13]
The status shows open or stopped regardless of the actual state and I am unable to open/close the door via Homebridge or my iDevice. The state doesn't change when the door is opened via the AladdinConnect app. The login credentials used are the primary user NOT a secondary user.

"accessories": [
        {
            "name": "AladdinConnectGarageDoorOpener",
            "username": "[primary account email address]",
            "password": "[password]",
            "status_update_delay": "20",
            "poll_state_delay": 30,
            "device_number": 0,
            "garage_number": 1,
            "log_polling": true,
            "allow_debug": true,
            "accessory": "AladdinConnectGarageDoorOpener"
        }
    ],

**Comment by apexad** [comment]
Are you getting any error messages or anything in the logs?

**Comment by nefarious-vw** [comment]
No errors and nothing in the logs. I've turned on polling and poll logging
and there isn't a single polling event in the logs.

**Comment by nefarious-vw** [comment]
Issue has been resolved (though I'm not sure why as I made no changes).

**Comment by apexad** [comment]
It may have been that the actual controller was out of sync and had times out attempting to open or close.
