### ISSUE TITLE
[Feature Request] Allow to manually set battery level range

### ISSUE THREAD

**Issue by dclowd9901** [iAnatoly/homebridge-aladdin-connect-garage-door#14]
Ability to set battery "full" value. System reports battery at 66%, but electrical test shows full (13.3v). It would be nice to be able to recalibrate the reporting so the system reported a more accurate percentage value.

**Comment by apexad** [comment]
13.3 volts!? The battery percentage shown is for the tilt sensor.

**Comment by dclowd9901** [comment]
Oh? I wasn’t aware. What is the tilt sensor?

**Comment by apexad** [comment]
So, to be clear, I've got the retrofit kit, so it requires that a tilt sensor with a small coin cell battery is installed on the Garage door itself that monitors if the door is vertical or horizontal (tilt sensor).

I'm assuming you are using this plugin with a garage door that has Aladdin Connect built in?  Do you need to have anything directly on the door?  What did you measure at 13.3 volts?

**Comment by dclowd9901** [comment]
Oh! The battery level is for the door sensor, I had no idea.

Mine was retrofit as well, but I also have a backup battery on my unit,
which is what I thought the battery measurement was referring to.

Thanks for the explanation! I wonder if Aladdin connect unit gets any info
on the backup battery health...
