### ISSUE TITLE
Transitions from open->closing->closed and closed->opening->open are not working properly

### ISSUE THREAD

**Issue by bc2297** [iAnatoly/homebridge-aladdin-connect-garage-door#15]
When I use hoobs to trigger the garage door to open or close, and watch the status of the garage door in the home app, the transitions don't update properly. What I see:

When opening door:
Closed->Opening->Closed->Open

When closing door:
Open->Closing->Open->Closed

Using:
Aladdin - 1.0.1
Hoobs - 3.3.1

"accessories": [
        {
            "accessory": "AladdinConnectGarageDoorOpener",
            "plugin_map": {
                "plugin_name": "homebridge-aladdin-connect-garage-door",
                "index": 0
            },
            "name": "GDoor",
            "status_update_delay": "30",
            "username": "redacted",
            "password": "redacted",
            "allow_debug": false,
            "log_polling": false,
            "ignore_errors": false,
            "battery_low_level": 5,
            "poll_state_delay": 30
        }
    ]

**Comment by apexad** [comment]
This may be an issue with the polling.  It is essentially polling the status of the door too soon and therefore facing the incorrect value mid-way through.  In your example, Closed->Opening->Closed->Open it is actually Closed->Opening->(Poll for value)Closed->Open

Probably need to disable polling for a set time when an action like Open/Close is sent.

**Comment by apexad** [comment]
Fixed https://github.com/iAnatoly/homebridge-aladdin-connect-garage-door/pull/16
