### ISSUE TITLE
Stuck in “Opening…” State on Load

### ISSUE THREAD

**Issue by kylewhirl** [iAnatoly/homebridge-aladdin-connect-garage-door#19]
Every time HomeBridge is restarted, the garage is stuck in a state of Opening… even though it is closed and not opening.

**Comment by apexad** [comment]
Sorry for not responding sooner. This likely means that Target state is Open and actual state is Closed.  Are you using polling?

**Comment by kylewhirl** [comment]
Yes I am. Every 10 seconds

**Comment by apexad** [comment]
So, when it polls does it get fixed?

**Comment by apexad** [comment]
I was able to duplicate this issue... if you control the garage door once using HomeKit/Siri it should resolve itself but I'll look into why this is happening.

**Comment by rucknapucknavitz** [comment]
> Yes I am. Every 10 seconds

I was *not* using polling and got this issue. Enabled polling (10 sec) and it seems to have gone away.

**Comment by djrobx** [comment]
I am experiencing this issue too.

![image](https://user-images.githubusercontent.com/1526865/126884780-fa6904bd-2a22-4edf-beaf-2110a4b45a9f.png)

If I close the home app and reopen it, I get a new status line showing the correct CLOSED status, it just seems like homekit isn't taking the plugin's word for it...

**Comment by apexad** [comment]
Well, there is both what the door is and what the target is. Something might be missing in setting one more f them correctly. Will take a look at this soon.

**Comment by jnubz** [comment]
FWIW, I have been messing around with this bug for a few weeks now. It seems like it always gets stuck in "Opening". Never "Closing". If you always use Siri, or the Home app, the status is accurate. If you use any of the physical remote buttons, or the Aladdin App, the Home App gets stuck in "Opening" on next launch.

The home app still tells you that it closed. It's almost like it is getting the response that the door has closed and Home.app is falsely "wanting" it to be open without actually sending the command.
