### ISSUE TITLE
What might be causing this to repeat?

### ISSUE THREAD

**Issue by hunt4868** [iAnatoly/homebridge-aladdin-connect-garage-door#21]
[Battery Level] characteristic value expected valid finite number and received "NaN" (number)

**Comment by apexad** [comment]
Hmmm... is everything else working as expected? Seems odd that it is unable to read your battery value if everything else is working.  However, I can put in a fix for this issue. The question I have is assuming it cannot read the battery value, should I report a low battery or just ignore battery level?

**Comment by apexad** [comment]
decided to report low battery if it cannot read it.

**Comment by hunt4868** [comment]
thanks for looking into this; im a bit confused because my equipment doesn't have a battery

**Comment by apexad** [comment]
oh! that makes sense... there are 2 kinds of genie openers... add on and built-in. The add on was a battery in the sensor which is attached to the garage door.

So, I'll swap this to be 100% for now so you don't get a warning

**Comment by apexad** [comment]
1.0.5 should fix this for ya!

**Comment by hunt4868** [comment]
awesome; thanks!!

**Comment by hunt4868** [comment]
also getting this one occasionally; not sure why:

The read handler for the characteristic 'Battery Level' on the accessory 'Aladdin' was slow to respond!

**Comment by apexad** [comment]
> also getting this one occasionally; not sure why:
> 
> The read handler for the characteristic 'Battery Level' on the accessory 'Aladdin' was slow to respond!

So, probably want to just make it so you can turn off battery level checking entirely. This is a bigger change.  I may save this for the re-write of this plugin/library.
