### ISSUE TITLE
Door Status Response Invalid

### ISSUE THREAD

**Issue by j-coates** [iAnatoly/homebridge-aladdin-connect-garage-door#25]
I've been trying to figure out why this plugin has just not worked for me at all recently. I've tracked it down to this error:
`[*] DEBUG: battery_level and link_status response: [{"id":1,"status":"invalid"},{"id":2,"status":"invalid"}]`
`[*] DEBUG: Error details: {}`
`[*] DEBUG: door_status response: [{"id":1,"status":"invalid"}]`
`[*] DEBUG: Error details: {}`

From my research, it gets the portal id and door id correctly, and I can run that command in cURL. My issue arises when I get to the status and the response I get is: 

`{`
`  "error": {`
`    "code": -1,`
`    "message": "JSON parse error"`
`  }`
`}`

So I guess I'm asking if anyone else is having this issue or if it's just my account or something.

**Comment by jcarusone1650** [comment]
Yes same for me and same error, just tried this plugin for the first time a few days ago and it the status reported to HomeKit is buggy.

**Comment by masterxchief46** [comment]
I am also seeing the same issue

**Comment by apexad** [comment]
Hope genie did not change the API. I will look at this soon.

**Comment by stanhodges** [comment]
Same issue for me. The Aladdin Connect app still works but the Homebridge connection is in a constant state of Closed. If I try to open view homebridge it does not do anything.

**Comment by hunt4868** [comment]
Any updates on this? Plugin no longer works at all

**Comment by jnubz** [comment]
Mine works perfectly if I never use the physical buttons for the garage door. If I just use Siri/Home.app, everything is perfect. Just seems to get stuck in "opening" or "closing" when a wall or remote button is used.

**Comment by apexad** [comment]
I will have time to look at this plugin again soon. Just moved and did a renovation so time has been tight. I still have a genie aladdin connect though.

**Comment by hunt4868** [comment]
Ever since HOOBS v4 I get errors related to: Bridge[*] DEBUG: door_status response: [{"id":1,"status":"invalid"}]

Any ideas?

**Comment by j-coates** [comment]
I did see where someone has said that Genie did a migration of their API and that's probably why it's not working: https://github.com/shoejosh/aladdin-connect/issues/5

**Comment by dmradcilff** [comment]
Would like to see this working but like others I am constantly getting the door opened/door closed messages in homekit.  The Genia app works flawlessly but for some reason homekit doesn't.
