### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by drinkey73** [iAnatoly/homebridge-aladdin-connect-garage-door#27]
I am using the following code from the Hoobs 4 plugin for Aladdin Connect and nothing is happing. 
{
    "accessories": [
        {
            "accessory": "AladdinConnectGarageDoorOpener",
            "name": "Garage Door",
            "status_update_delay": 15,
            "poll_state_delay": 20,
            "device_number": 0,
            "garage_number": 1,
            "battery_low_level": 15,
            "ignore_errors": false,
            "log_polling": false,
            "allow_debug": false,
            "username": "drinkey@gmail.com",
            "password": "#########"
        }
    ],
    "platforms": []
}

It installs fine and adds to HomeKit fine even shows the door open and close but nothing actually happens to the garage door.  I am using the ower account information as I am the owner.  please help.

**Comment by j-coates** [comment]
This is going to be related to #25 . I believe the API has changed how it parses the commands, so it's currently not working.

**Comment by drinkey73** [comment]
So at this point no way to have my Aladdin Connect door to actually open using HK and Hoobs 4. 😢

**Comment by KalvinMac** [comment]
any update?

**Comment by drinkey73** [comment]
Nothing has worked and no one’s that I have found seems to know.  So for now I got a Meross GDO until connect works with HK or something is fixed.

**Comment by donjalex2** [comment]
Have you tried this plugin?  https://github.com/derek-miller/homebridge-genie-aladdin-connect#readme.   The only problem I'm having with this plugin created by derek-miller is it will only show one of my two garage doors.  It used to show both, but as of yesterday it only shows one garage door.  If you only have one garage door, this plugin i mention works good.

**Comment by donjalex2** [comment]
how do you add two doors in code?

**Comment by derek-miller** [comment]
@donjalex2 Sharing your [comment](https://github.com/derek-miller/homebridge-genie-aladdin-connect/issues/2#issuecomment-1014627631 ) regarding the exosite api being deprecated in case others find this issue.

**Comment by apexad** [comment]
@iAnatoly what do you say to retiring this plugin in favor of the one created by @derek-miller 
I don't have the time at the moment to do the re-write I was planning to do and now with the new API it's a bit moot anyway and @derek-miller already has a great plugin.

**Comment by iAnatoly** [comment]
@apexad, I also do not have much time or will for maintaining this plugin at the moment.
Given that there is a well-maintained alternative available, it does seem like a good idea to retire this one.

**Comment by jnubz** [comment]
The alternative is not homebridge verified. Not actually sure whether that really means anything, but it does seem to work. Time is hard to find these days.

**Comment by apexad** [comment]
@jnubz It just means the developer has not submitted it to get verified.

@derek-miller That is something you need to do. Info here: https://github.com/homebridge/verified

Otherwise I will be pulling node-aladdin-connect and this homebridge plugin from npm later today. I'll probably fork your plugin @derek-miller and check it out. If there is anything I can help with by creating a PR, I will. I'm hoping to have more time in the coming days and weeks to work on my homebridge plugins again, but having one off my plate is definitely a plus.

**Comment by apexad** [comment]
It's official.

This package is deprecated, please use https://github.com/derek-miller/homebridge-genie-aladdin-connect (https://www.npmjs.com/package/homebridge-aladdin-connect-garage-door) instead

**Comment by derek-miller** [comment]
RE [this](https://github.com/iAnatoly/homebridge-aladdin-connect-garage-door/issues/27#issuecomment-1025005140) comment, I submitted my plugin for verification. https://github.com/homebridge/verified/issues/385 🤞🏻
