### ISSUE TITLE
Always announces Door status in Apple Home app with HOOBS services restart

### ISSUE THREAD

**Issue by ocjay** [iAnatoly/homebridge-aladdin-connect-garage-door#8]
First of all thank you for the plugin. Works well so far. 
The following is really not a bug but an enhancement request: When Home Bridge/HOOBS restarts services/plugins, this plugin announces to Apple Homekit/Home app and to the user the status of the garage doors even when the user is not actively using the Home app. I have 3 garage doors and my wife thought it was funny at first but now is wondering if she is going to be notified in the middle of the night with the status of the garage doors.
Please enhance so that just the status when in the Home app is updated when services are restarted and the user is not formally notified of the status of the garage doors.
Thank you
Jay

**Comment by apexad** [comment]
As far as I can tell, this is an issue with HomeKit itself.  The default for a Garage Door is 'Open' so if Homebridge/HOOBS restarts this is set until It is able to fetch he real status (which may be 'Closed') and update it.

The bigger question to ask is why is Homebridge/HOOBS Restarting?  One of your plugins is causing it to crash and that is what you need to investigate.  If you are able to obtain some error logs or something and determine it is in fact this plugin, please re-open this issue and add more details.

**Comment by ocjay** [comment]
Okay thanks for the response. 
The restart of HomeKit/HOOBS was mostly me setting it up making config changes and adding plugins. Anytime you seem to make and save a configuration change the services/plugins restart. 

Thank you Jay
